[project]
name = "personal-ai-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "customtkinter>=5.2.2",
    "pillow>=10.4.0",
    "pynput>=1.8.1",
    "pystray>=0.19.5",
    "tkhtmlview>=0.3.1",
]
